version: '3.8'

services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"

  message-processor:
    build: ./message-processor
    container_name: message-processor
    stdin_open: true
    tty: true
    environment:
      - VOSK_LOG_LEVEL=-1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./message-processor:/app
      - ./data:/data  # Bind mount for the data directory
    depends_on:
      - redis

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5001:5001"  # Changed to map host port 5001 to container port 5001
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_USERNAME=${API_USERNAME}
      - API_PASSWORD=${API_PASSWORD}
      - API_PORT=${API_PORT}
    volumes:
      - ./api:/app
    depends_on:
      - redis