version: '3.8'

services:
  redis:
    image: "redis:alpine"
    container_name: redis
    expose:
      - "6379"
    networks:
      - internal

  message-processor:
    build: ./message-processor
    container_name: message-processor
    stdin_open: true
    tty: true
    environment:
      - VOSK_LOG_LEVEL=-1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./message-processor:/app
      - ./data:/data  # Bind mount for the data directory
    depends_on:
      - redis
    networks:
      - internal

  api:
    build: ./api
    ports:
      - "${API_HOST_PORT:-5000}:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FLASK_DEBUG=${FLASK_DEBUG:-0}
      - FLASK_ENV=${FLASK_ENV:-development}
      - API_USERNAME=${API_USERNAME}
      - API_PASSWORD=${API_PASSWORD}
    volumes:
      - ./api:/app
    depends_on:
      - redis
    networks:
      - internal

networks:
  internal:
    driver: bridge